---
# ansible-playbook -i ./hosts main.yaml --ask-become-pass
- name: "installing docker via ansible"
  hosts: webserver
  become_user: root
  become: true
  #become_method: sudo 
  tasks: 
    - name: Install pip
      apt: name=python-pip state=present

    - name: install pip3
      apt: name=python3-pip state=present

    - name: Uninstall docker-python
      pip: name=docker-py state=present

    - name: Docker image
      docker_container:
        name: web
        image: alpine:3.11.5
        #state: stopped
        command: ["sleep" , "infinity"]

    - name: Docker image from hub 
      docker_container:
        name: nginx
        image: nginx:1.17.9
        state: started